# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  lane :release do
    swift_file_path = "./Sources/KovaleeSDK/Kovalee.swift"
    version = bump_version
    handle_git(version, [swift_file_path])
  end

  lane :bump_version do |options|
    bump_type = options[:type] || "patch"
    current_version = read_version_from_swift
    new_version = bump_version_string(current_version, bump_type)
    
    UI.message("Bumping version from #{current_version} to #{new_version}")
    update_version_in_swift(new_version)
    
    UI.success("Version bumped to #{new_version}")
    new_version
  end

end

def update_version_in_swift(new_version)
  file_path = "../Sources/KovaleeSDK/Kovalee.swift"
  text = File.read(file_path)
  new_contents = text.gsub(/(let SDK_VERSION = ")[^"]+/, "\\1#{new_version}")

  # Write changes to the file
  File.open(file_path, "w") {|file| file.puts new_contents}
end

def read_version_from_swift
  file_path = "../Sources/KovaleeSDK/Kovalee.swift"
  text = File.read(file_path)
  match = text.match(/let SDK_VERSION = "([^"]+)"/)
  
  if match && match[1]
    return match[1]
  else
    UI.user_error!("Could not find SDK_VERSION in #{file_path}")
  end
end

def bump_version_string(version, type)
  parts = version.split(".").map(&:to_i)
  
  case type.downcase
  when "major"
    parts[0] += 1
    parts[1] = 0
    parts[2] = 0
  when "minor"
    parts[1] += 1
    parts[2] = 0
  when "patch"
    parts[2] += 1
  else
    UI.user_error!("Invalid bump type: #{type}. Use 'major', 'minor', or 'patch'")
  end
  
  parts.join(".")
end

def handle_git(new_version, paths) 
  git_add
  git_commit(
    path: paths,
    message: "#{new_version} release"
  )

  add_git_tag(tag: "#{new_version}")
  push_to_git_remote
end 